---
services:
  backend:
#    image: ghcr.io/lorddistrict/crontab-api:latest
    build: .
    restart: unless-stopped
    volumes:
      - ./api:/var/www/html
      - ./config/docker/backend/000-default.conf:/etc/apache2/sites-available/000-default.conf
    labels:
      - traefik.http.services.backend.loadbalancer.server.port=80
    networks:
      - my-network

  traefik:
    image: traefik:v2.7
    command: --api.insecure=true --providers.docker
    depends_on:
      - backend
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    ports:
      - "80:80"
      - "8080:8080"
    networks:
      - my-network

networks:
  my-network:
    external: true
