services:
  php:
    image: chialab/php-dev:8.1-apache
    restart: unless-stopped
    ports:
      - "127.0.0.1:9090:80"
    volumes:
      - ./api:/var/www/html
      - ./config/docker/php/000-default.conf:/etc/apache2/sites-available/000-default.conf
