---
services:
  backend:
    build: .
    restart: unless-stopped
    volumes:
      - ./api:/var/www/html
      - ./config/docker/backend/000-default.conf:/etc/apache2/sites-available/000-default.conf
