on:
  pull_request:
    types:
      - opened
      - reopened
      - edited
      - synchronize

env:
  DOCKER_SERVICE_NAME: backend
  API_IMAGE_NAME: $DOCKER_SERVICE_NAME

jobs:
#  build:
#    name: Build & Push image
#    runs-on: ubuntu-latest
#    steps:
#      - uses: actions/checkout@v2
#      - uses: rlespinasse/github-slug-action@v4
#      - name: Build and Publish API
#        uses: elgohr/Publish-Docker-Github-Action@master
#        with:
#          name: Lorddistrict/dynamic-branch-deployer/$API_IMAGE_NAME:${{ env.GITHUB_HEAD_REF_SLUG }}
#          username: ${{ github.actor }}
#          password: ${{ secrets.GITHUB_TOKEN }}
#          registry: ghcr.io
  deploy:
    name: Login to Github Repository & Deploy
    runs-on: ubuntu-latest
#    needs: [ build ]
    steps:
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: rlespinasse/github-slug-action@v4
      - name: Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_SERVER }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            echo config/docker/${{ env.DOCKER_SERVICE_NAME }}/branch_template.conf
            cd /home/github_actions/dynamic-branch-deployer
            docker compose pull || true
            docker compose build
            docker compose -p ${{ env.GITHUB_HEAD_REF_SLUG }} up -d
            docker compose exec ${{ env.DOCKER_SERVICE_NAME }} composer install
            cat config/docker/${{ env.DOCKER_SERVICE_NAME }}/branch_template.conf > /etc/nginx/sites-available/${{ env.GITHUB_HEAD_REF_SLUG }}.conf
            ln -sf /etc/nginx/sites-available/${{ env.GITHUB_HEAD_REF_SLUG }}.conf /etc/nginx/sites-enabled/${{ env.GITHUB_HEAD_REF_SLUG }}.conf
            sed -i "s/docker_service_port/$(docker port ${{ env.GITHUB_HEAD_REF_SLUG }}-${{ env.DOCKER_SERVICE_NAME }}-1 | awk -F':' '{print $2}' | tr -d '\n')/g" /etc/nginx/sites-available/${{ env.GITHUB_HEAD_REF_SLUG }}.conf
            sudo /usr/sbin/service nginx restart
