on:
  pull_request:
    types:
      - opened
      - reopened
      - edited
      - synchronize
jobs:
  build:
    name: Build & Push image
    runs-on: ubuntu-latest
    steps:
      - name: Get branch name
        id: branch-name
        uses: tj-actions/branch-names@v5.2
      - uses: actions/checkout@v2
      - name: Build and Publish API
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          name: Lorddistrict/dynamic-branch-deployer/crontab-api:${{ steps.branch-name.outputs.current_branch }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: ghcr.io
  deploy:
    name: Login to Github Repository & Deploy
    runs-on: ubuntu-latest
    needs: [ build ]
    steps:
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: rlespinasse/github-slug-action@v4
      - name: Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_SERVER }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            docker_service_name="backend"
            nginx_config_file_name=${{ env.GITHUB_REF_SLUG }}.conf
            cd /home/github_actions/dynamic-branch-deployer
            docker compose pull || true
            docker compose build
            docker compose -p ${{ env.GITHUB_REF_SLUG }} up -d
            docker compose exec $(docker_service_name) composer install
            cat config/docker/$(docker_service_name)/branch_template.conf > /etc/nginx/sites-available/$(nginx_config_file_name)
            ln -s /etc/nginx/sites-available/$(nginx_config_file_name) /etc/nginx/sites-enabled/$(nginx_config_file_name)
            sed -i "s/docker_service_port/$(docker port ${{ env.GITHUB_REF_SLUG }}-$(docker_service_name)-1 | awk -F':' '{print $2}' | tr -d '\n')/g" /etc/nginx/sites-available/$(nginx_config_file_name)
